"""
Neural Network Embedding Classifier for CLIP Few-Shot

Train a small MLP on CLIP embeddings (support-set) and use it for inference.
- Trains on support-set features provided by SupportSetManager/FeatureExtractor
- Saves/loads model with metadata (class names, input dim, config)
- Predicts probabilities with softmax

Design goals:
- Lightweight, dependency-free (PyTorch only)
- Robust to small datasets via dropout and early stopping
- Works on CPU by default
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from ..features.dim_reducer import DimensionalityReducer, DimReduceConfig


Tensorable = Union[np.ndarray, torch.Tensor]
# --- Classes I/O helpers (save/load classes.py next to model) ---
import ast


def _save_classes_py(dir_path: Path, class_names: List[str]) -> Path:
    """Save classes.py with a top-level `classes` list next to the model."""
    dir_path.mkdir(parents=True, exist_ok=True)
    f = dir_path / "classes.py"
    lines = [
        "# Auto-generated by SVMClassifier/NNClassifier. Do not edit manually unless you know what you're doing.",
        "# -*- coding: utf-8 -*-",
        "classes = [",
    ]
    for name in class_names:
        lines.append(f"    {name!r},")
    lines.append("]\n")
    f.write_text("\n".join(lines), encoding="utf-8")
    return f


def _load_classes_from_py(dir_path: Path) -> Optional[List[str]]:
    f = dir_path / "classes.py"
    if not f.exists():
        return None
    try:
        src = f.read_text(encoding="utf-8")
        tree = ast.parse(src)
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == "classes":
                        if isinstance(node.value, (ast.List, ast.Tuple)):
                            vals: List[str] = []
                            for elt in node.value.elts:
                                if isinstance(elt, ast.Constant) and isinstance(
                                    elt.value, str
                                ):
                                    vals.append(elt.value)
                            if vals:
                                return vals
        return None
    except Exception:
        return None


@dataclass
class NNConfig:
    # Architecture
    hidden_sizes: List[int] = None  # e.g., [512] or [512, 256]
    activation: str = "relu"  # 'relu' | 'gelu' | 'tanh'
    dropout: float = 0.1

    # Training
    epochs: int = 20
    lr: float = 1e-3
    weight_decay: float = 1e-4
    batch_size: int = 64
    early_stopping_patience: int = 5
    class_weight_balanced: bool = True

    # Features and persistence
    feature_layer: str = "global"  # currently only 'global' is supported
    model_path: Optional[str] = None
    device: str = "cpu"  # train/infer device for the head only

    def __post_init__(self):
        if self.hidden_sizes is None:
            self.hidden_sizes = [512]


class _EmbDataset(Dataset):
    def __init__(self, X: torch.Tensor, y: torch.Tensor):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


class _MLP(nn.Module):
    def __init__(
        self, in_dim: int, num_classes: int, hidden: List[int], act: str, dropout: float
    ):
        super().__init__()
        dims = [in_dim] + list(hidden)
        layers: List[nn.Module] = []
        for i in range(len(dims) - 1):
            layers.append(nn.Linear(dims[i], dims[i + 1]))
            if act == "relu":
                layers.append(nn.ReLU(inplace=True))
            elif act == "gelu":
                layers.append(nn.GELU())
            elif act == "tanh":
                layers.append(nn.Tanh())
            else:
                layers.append(nn.ReLU(inplace=True))
            if dropout > 0:
                layers.append(nn.Dropout(p=dropout))
        layers.append(nn.Linear(dims[-1], num_classes))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class NNClassifier:
    def __init__(self, class_names: List[str], cfg: Optional[NNConfig] = None):
        self.class_names = list(class_names)
        self.cfg = cfg or NNConfig()
        self.model: Optional[_MLP] = None
        self.input_dim: Optional[int] = None
        # Optional dimensionality reducer applied on visual embeddings
        self.reducer: Optional[DimensionalityReducer] = None

    # ---------- Utilities ----------
    @staticmethod
    def _to_tensor(x: Tensorable) -> torch.Tensor:
        if isinstance(x, torch.Tensor):
            return x
        return torch.tensor(np.asarray(x))

    @staticmethod
    def _normalize(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
        return x / (x.norm(dim=dim, keepdim=True) + 1e-8)

    # ---------- Data collection from SupportSetManager ----------
    def _collect_training_data(
        self,
        support_manager,
        feature_layer: str,
        text_features: Optional[Dict[str, torch.Tensor]] = None,
        use_text_sim_features: bool = False,
        beta: float = 0.5,
    ) -> Tuple[torch.Tensor, torch.Tensor, int]:
        """
        Build (X, y) for NN head training.
        Preferred order:
        1) If support_images are available, re-extract embeddings via feature_extractor (original path)
        2) Else, use adapter_support_bank (global features per shot) restored from prototypes.json
        3) Else, fall back to class global prototypes from prototypes.json
        Returns X [N, D], y [N], and inferred input_dim D.
        """
        X_list: List[torch.Tensor] = []
        y_list: List[int] = []

        # Strict policy: train only from per-image embeddings (raw), no prototypes fallback
        # 1) If support_manager has embed_records (from images or embed.json), use them directly
        used_records = False
        try:
            if isinstance(getattr(support_manager, "embed_records", None), dict):
                for ci, cname in enumerate(support_manager.class_names):
                    for rec in support_manager.embed_records.get(cname, []):
                        g = rec.get("global", None)
                        if g is None:
                            continue
                        t = torch.tensor(np.asarray(g).reshape(-1), dtype=torch.float32)
                        X_list.append(t)
                        y_list.append(ci)
                used_records = any(
                    len(support_manager.embed_records.get(c, [])) > 0
                    for c in support_manager.class_names
                )
        except Exception:
            used_records = False

        # 2) Otherwise, if adapter_support_bank exists and source is 'embed' or 'images', use it
        if not X_list and getattr(support_manager, "embedding_source", None) in (
            "embed",
            "images",
        ):
            for ci, cname in enumerate(support_manager.class_names):
                bank = getattr(support_manager, "adapter_support_bank", {}).get(cname)
                if (
                    bank is None
                    or not isinstance(bank, torch.Tensor)
                    or bank.numel() == 0
                ):
                    continue
                B = bank.detach().cpu().float()
                for j in range(B.shape[0]):
                    X_list.append(B[j])
                    y_list.append(ci)

        # Do NOT fallback to class prototypes; enforce raw per-image embeddings only
        if not X_list:
            raise RuntimeError(
                "No per-image embeddings available for NN training. Ensure embed.json exists or refresh support set."
            )

        X = torch.stack(X_list, dim=0)
        # L2-normalize features for stable training while keeping raw cache intact
        X = self._normalize(X, dim=-1)
        y = torch.tensor(y_list, dtype=torch.long)

        # Optional: augment with text similarity vector [C]
        if use_text_sim_features and text_features is not None:
            try:
                device = X.device
                # Build [C, D] matrix in class order
                T_list: List[torch.Tensor] = []
                for cname in self.class_names:
                    tf = text_features.get(cname, None)
                    if tf is None:
                        raise KeyError(f"Missing text feature for class: {cname}")
                    if not isinstance(tf, torch.Tensor):
                        tf = torch.tensor(np.asarray(tf), dtype=torch.float32)
                    tf = tf.reshape(-1)
                    tf = tf / (tf.norm() + 1e-8)
                    T_list.append(tf)
                T = torch.stack(T_list, dim=0).to(device)  # [C, D]
                S = X @ T.t()  # [N, C]
                mu = S.mean(dim=1, keepdim=True)
                sd = S.std(dim=1, keepdim=True) + 1e-8
                Sz = (S - mu) / sd
                X = torch.cat([X, (float(beta) * Sz)], dim=1)
            except Exception:
                pass

        D = X.shape[-1]
        return X, y, D

    # ---------- Training ----------
    def fit_from_support_manager(
        self,
        support_manager,
        feature_layer: Optional[str] = None,
        text_features: Optional[Dict[str, torch.Tensor]] = None,
        use_text_sim_features: bool = False,
        beta: float = 0.5,
    ) -> None:
        fl = feature_layer or self.cfg.feature_layer
        X, y, in_dim = self._collect_training_data(
            support_manager,
            fl,
            text_features=text_features,
            use_text_sim_features=use_text_sim_features,
            beta=beta,
        )
        num_classes = len(self.class_names)

        # Optional: dimensionality reduction on visual part before training
        try:
            cc = getattr(
                getattr(support_manager, "config", None), "classification", None
            )
            dr_enable = (
                bool(getattr(cc, "enable_dim_reduction", False))
                if cc is not None
                else False
            )
            if dr_enable:
                # Split visual/text parts if text sims appended
                if use_text_sim_features:
                    C = len(self.class_names)
                    X_vis = X[:, :-C]
                    X_txt = X[:, -C:]
                else:
                    X_vis = X
                    X_txt = None
                dr_cfg = DimReduceConfig(
                    method=str(getattr(cc, "dim_reduction_method", "pca")),
                    n_components=getattr(cc, "dim_reduction_n_components", 0.95),
                    whiten=bool(getattr(cc, "dim_reduction_whiten", False)),
                    random_state=getattr(cc, "dim_reduction_random_state", 42),
                )
                self.reducer = DimensionalityReducer(dr_cfg).fit(X_vis)
                X_vis_dr = self.reducer.transform(X_vis)
                X = (
                    torch.cat([X_vis_dr, X_txt], dim=1)
                    if X_txt is not None
                    else X_vis_dr
                )
        except Exception:
            self.reducer = None
        # Update input dim after DR
        self.input_dim = int(X.shape[-1])

        # Model
        self.model = _MLP(
            self.input_dim,
            num_classes,
            self.cfg.hidden_sizes,
            self.cfg.activation,
            self.cfg.dropout,
        )
        device = torch.device(
            self.cfg.device if isinstance(self.cfg.device, str) else "cpu"
        )
        self.model.to(device)

        # Split train/val (small stratified split)
        N = X.shape[0]
        if N >= 10 and len(set(y.tolist())) > 1:
            # 80/20 split per class
            idxs_by_c: Dict[int, List[int]] = {}
            for i, t in enumerate(y.tolist()):
                idxs_by_c.setdefault(t, []).append(i)
            train_idx: List[int] = []
            val_idx: List[int] = []
            for _, idxs in idxs_by_c.items():
                k = max(1, int(0.2 * len(idxs)))
                val_idx.extend(idxs[:k])
                train_idx.extend(idxs[k:])
            if not train_idx:  # fallback
                train_idx, val_idx = list(range(N)), []
        else:
            train_idx, val_idx = list(range(N)), []

        X_train = X[train_idx]
        y_train = y[train_idx]
        X_val = X[val_idx] if val_idx else None
        y_val = y[val_idx] if val_idx else None

        # Class weights
        if self.cfg.class_weight_balanced:
            unique, counts = torch.unique(y_train, return_counts=True)
            weights = torch.ones(num_classes, dtype=torch.float32)
            for u, c in zip(unique.tolist(), counts.tolist()):
                weights[u] = float(len(y_train)) / (num_classes * float(c))
            criterion = nn.CrossEntropyLoss(weight=weights.to(device))
        else:
            criterion = nn.CrossEntropyLoss()

        optimizer = torch.optim.AdamW(
            self.model.parameters(), lr=self.cfg.lr, weight_decay=self.cfg.weight_decay
        )

        # Dataloaders
        train_loader = DataLoader(
            _EmbDataset(X_train, y_train),
            batch_size=min(self.cfg.batch_size, max(1, len(X_train))),
            shuffle=True,
        )
        val_loader = (
            DataLoader(_EmbDataset(X_val, y_val), batch_size=len(X_val))
            if X_val is not None
            else None
        )

        best_val = float("inf")
        patience = self.cfg.early_stopping_patience
        no_improve = 0

        self.model.train()
        for epoch in range(self.cfg.epochs):
            running = 0.0
            n_samples = 0
            for xb, yb in train_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                logits = self.model(xb)
                loss = criterion(logits, yb)
                optimizer.zero_grad(set_to_none=True)
                loss.backward()
                optimizer.step()
                running += float(loss.detach().cpu().item()) * xb.size(0)
                n_samples += xb.size(0)
            train_loss = running / max(1, n_samples)

            # Validation
            if val_loader is not None:
                self.model.eval()
                with torch.no_grad():
                    v_running = 0.0
                    v_n = 0
                    for xb, yb in val_loader:
                        xb = xb.to(device)
                        yb = yb.to(device)
                        logits = self.model(xb)
                        loss = criterion(logits, yb)
                        v_running += float(loss.detach().cpu().item()) * xb.size(0)
                        v_n += xb.size(0)
                    val_loss = v_running / max(1, v_n)
                self.model.train()
                if val_loss + 1e-6 < best_val:
                    best_val = val_loss
                    no_improve = 0
                    best_state = {
                        k: v.cpu() for k, v in self.model.state_dict().items()
                    }
                else:
                    no_improve += 1
                    if no_improve >= patience:
                        # Early stop and restore best
                        if "best_state" in locals():
                            self.model.load_state_dict(best_state)
                        break

        # Final eval mode
        self.model.eval()

    # ---------- Prediction ----------
    @torch.no_grad()
    def predict_from_features(self, feat: Tensorable) -> Tuple[str, Dict[str, float]]:
        if self.model is None:
            raise RuntimeError("NN model is not initialized")
        x = self._to_tensor(feat).float()
        if x.dim() == 2 and x.shape[0] == 1:
            x = x.squeeze(0)
        if x.dim() != 1:
            raise ValueError("Expected 1D feature vector for prediction")
        x = self._normalize(x)
        # Optional DR
        try:
            if getattr(self, "reducer", None) is not None:
                x = self.reducer.transform(x)
        except Exception:
            pass
        # Pad zeros if model expects additional text-sim dims (we don't reconstruct at inference here)
        if (
            self.input_dim is not None
            and x.dim() == 1
            and x.shape[-1] < int(self.input_dim)
        ):
            pad = int(self.input_dim) - int(x.shape[-1])
            x = torch.cat([x, torch.zeros(pad, dtype=x.dtype)], dim=0)
        x = x.unsqueeze(0)
        device = next(self.model.parameters()).device
        x = x.to(device)
        logits = self.model(x)  # [1, C]
        probs = F.softmax(logits, dim=-1).squeeze(0).cpu().numpy()
        idx = int(np.argmax(probs))
        cls = self.class_names[idx]
        score_dict = {
            self.class_names[i]: float(probs[i]) for i in range(len(self.class_names))
        }
        return cls, score_dict

    # ---------- Persistence ----------
    def save(self, path: Union[str, Path]) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        meta = {
            "class_names": self.class_names,
            "input_dim": self.input_dim,
            "cfg": asdict(self.cfg),
            "reducer": (
                self.reducer.serialize()
                if getattr(self, "reducer", None) is not None
                else None
            ),
        }
        data = {
            "state_dict": self.model.state_dict() if self.model is not None else None,
            "meta": meta,
        }
        torch.save(data, p)
        # Also persist classes.py next to the model for downstream usage
        try:
            _save_classes_py(p.parent, self.class_names)
        except Exception:
            pass
        return p

    @staticmethod
    def load(path: Union[str, Path]) -> "NNClassifier":
        p = Path(path)
        data = torch.load(p, map_location="cpu")
        meta = data.get("meta", {})
        cfg_dict = meta.get("cfg", {})
        cfg = NNConfig(**cfg_dict) if cfg_dict else NNConfig()
        input_dim = int(meta.get("input_dim", 0))
        model_state = data.get("state_dict", None)
        # Prefer classes.py next to the model; fallback to embedded metadata
        override = _load_classes_from_py(p.parent)
        class_names = override if override else meta.get("class_names", [])
        clf = NNClassifier(class_names, cfg)
        if input_dim <= 0:
            raise RuntimeError("Invalid input_dim in saved NN model")
        clf.input_dim = input_dim
        clf.model = _MLP(
            input_dim, len(class_names), cfg.hidden_sizes, cfg.activation, cfg.dropout
        )
        # Restore reducer if present
        try:
            red_blob = meta.get("reducer", None)
            if red_blob is not None:
                clf.reducer = DimensionalityReducer.deserialize(red_blob)
        except Exception:
            clf.reducer = None
        if model_state is not None:
            clf.model.load_state_dict(model_state)
        clf.model.eval()
        return clf


# Convenience factory
def create_nn_classifier(
    class_names: List[str], cfg: Optional[NNConfig] = None
) -> NNClassifier:
    return NNClassifier(class_names, cfg)
