"""
SVM-based Embedding Classifier for CLIP Few-Shot

This module provides an optional SVM classifier trained on support-set embeddings.
It is lightweight, easy to persist, and integrates with the existing pipeline.

- Trains on embeddings extracted from the support set (default: global CLIP features)
- Manages save/load via joblib
- Predicts class probabilities or calibrated scores

English + 中文注释，代码与注释使用英文，文档提供中英文。
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import torch

from ..features.dim_reducer import DimensionalityReducer, DimReduceConfig

try:
    from sklearn.svm import SVC
    from sklearn.preprocessing import LabelEncoder
    from sklearn.utils.class_weight import compute_class_weight
    import joblib
except Exception as e:  # pragma: no cover
    SVC = None  # type: ignore
    LabelEncoder = None  # type: ignore
    joblib = None  # type: ignore

# --- Classes I/O helpers (save/load classes.py next to model) ---
from typing import Any
import ast


def _save_classes_py(dir_path: Path, class_names: List[str]) -> Path:
    """
    Save an authoritative classes.py file alongside the model.
    The file defines a top-level variable `classes` listing all class names.
    """
    dir_path.mkdir(parents=True, exist_ok=True)
    f = dir_path / "classes.py"
    # English-only code and comments; content is simple and robust to parse
    lines = [
        "# Auto-generated by SVMClassifier/NNClassifier. Do not edit manually unless you know what you're doing.",
        "# -*- coding: utf-8 -*-",
        "classes = [",
    ]
    for name in class_names:
        lines.append(f"    {name!r},")
    lines.append("]\n")
    f.write_text("\n".join(lines), encoding="utf-8")
    return f


def _load_classes_from_py(dir_path: Path) -> Optional[List[str]]:
    """Load classes list from classes.py without executing arbitrary code (AST parse)."""
    f = dir_path / "classes.py"
    if not f.exists():
        return None
    try:
        src = f.read_text(encoding="utf-8")
        tree = ast.parse(src)
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == "classes":
                        if isinstance(node.value, (ast.List, ast.Tuple)):
                            vals: List[str] = []
                            for elt in node.value.elts:
                                if isinstance(elt, ast.Constant) and isinstance(
                                    elt.value, str
                                ):
                                    vals.append(elt.value)
                            if vals:
                                return vals
        return None
    except Exception:
        return None


@dataclass
class SVMConfig:
    kernel: str = "rbf"
    C: float = 1.0
    gamma: Union[str, float] = "scale"
    probability: bool = True
    feature_layer: str = "global"
    use_class_weight: bool = True


class SVMClassifier:
    """
    A thin wrapper around sklearn.svm.SVC for few-shot embedding classification.

    - fit_from_support_manager: build X/y from SupportSetManager
    - predict_from_features: accept pre-extracted features to avoid re-encoding
    - save/load: persist model with metadata
    """

    def __init__(self, class_names: List[str], cfg: Optional[SVMConfig] = None):
        if SVC is None:
            raise ImportError(
                "scikit-learn is required for SVMClassifier. Please install scikit-learn."
            )
        self.cfg = cfg or SVMConfig()
        self.class_names = list(class_names)
        self.label_encoder = LabelEncoder()
        # LabelEncoder sorts classes alphabetically; persist that order for consistency
        self.label_encoder.fit(self.class_names)
        self.class_names = list(self.label_encoder.classes_)
        self.model = None
        self.feature_dim: Optional[int] = None
        # Optional dimensionality reducer fitted on visual embeddings
        self.reducer: Optional[DimensionalityReducer] = None

    @property
    def is_trained(self) -> bool:
        return self.model is not None

    # --------------------------- Training ---------------------------
    def fit(self, X: np.ndarray, y: List[str]) -> None:
        """Fit SVM on embeddings.
        X: [N, D] float32/float64; y: class name strings
        """
        assert X.ndim == 2, "X should be 2D [N, D]"
        self.feature_dim = X.shape[1]
        y_idx = self.label_encoder.transform(y)

        class_weight = None
        if self.cfg.use_class_weight:
            classes = np.unique(y_idx)
            weights = compute_class_weight(
                class_weight="balanced", classes=classes, y=y_idx
            )
            class_weight = {int(c): float(w) for c, w in zip(classes, weights)}

        self.model = SVC(
            kernel=self.cfg.kernel,
            C=self.cfg.C,
            gamma=self.cfg.gamma,
            probability=self.cfg.probability,
            class_weight=class_weight,
        )
        self.model.fit(X, y_idx)

    def fit_from_support_manager(
        self,
        support_manager,
        feature_layer: Optional[str] = None,
        text_features: Optional[Dict[str, Union[np.ndarray, torch.Tensor]]] = None,
        use_text_sim_features: bool = False,
        beta: float = 0.5,
    ) -> None:
        """Build training set from SupportSetManager per-image embeddings.
        Optionally augment each sample with its cosine similarity to all class text features.
        """
        layer = feature_layer or self.cfg.feature_layer
        X_list: List[np.ndarray] = []
        y_list: List[str] = []

        # Strict policy: train only from per-image embeddings (raw), no prototypes fallback
        # Preferred: use per-image records (from embed.json or images processing)
        used_records = False
        try:
            if isinstance(getattr(support_manager, "embed_records", None), dict):
                for cname in support_manager.class_names:
                    recs = support_manager.embed_records.get(cname, [])
                    if recs:
                        Xc = np.stack(
                            [
                                np.asarray(
                                    r.get("global", []), dtype=np.float32
                                ).reshape(-1)
                                for r in recs
                                if r.get("global") is not None
                            ],
                            axis=0,
                        )
                        if Xc.size > 0:
                            X_list.append(Xc)
                            y_list.extend([cname] * Xc.shape[0])
                            used_records = True
        except Exception:
            used_records = False

        # Otherwise, if adapter_support_bank exists and source is 'embed' or 'images', use it
        if not used_records and getattr(support_manager, "embedding_source", None) in (
            "embed",
            "images",
        ):
            for cname in support_manager.class_names:
                bank = support_manager.adapter_support_bank.get(cname)
                if (
                    bank is not None
                    and isinstance(bank, torch.Tensor)
                    and bank.numel() > 0
                ):
                    Xc = bank.detach().cpu().numpy()
                    X_list.append(Xc)
                    y_list.extend([cname] * Xc.shape[0])

        if not X_list:
            raise RuntimeError(
                "No per-image embeddings available for SVM training. Ensure embed.json exists or refresh support set."
            )

        # Concatenate and L2-normalize base visual features
        X = np.concatenate(X_list, axis=0).astype(np.float32)
        norms = np.linalg.norm(X, axis=1, keepdims=True) + 1e-8
        Xn = X / norms  # visual normalized, before reduction

        # Optional: dimensionality reduction on visual features (fit on support-set)
        X_base = Xn
        try:
            cc = getattr(
                getattr(support_manager, "config", None), "classification", None
            )
            dr_enable = (
                bool(getattr(cc, "enable_dim_reduction", False))
                if cc is not None
                else False
            )
            if dr_enable:
                dr_cfg = DimReduceConfig(
                    method=str(getattr(cc, "dim_reduction_method", "pca")),
                    n_components=getattr(cc, "dim_reduction_n_components", 0.95),
                    whiten=bool(getattr(cc, "dim_reduction_whiten", False)),
                    random_state=getattr(cc, "dim_reduction_random_state", 42),
                )
                self.reducer = DimensionalityReducer(dr_cfg).fit(Xn)
                X_base = self.reducer.transform(Xn).astype(np.float32)
        except Exception:
            # If DR fails for any reason, fall back silently to original Xn
            self.reducer = None
            X_base = Xn

        # Optional: augment with text similarity vector [C] in class_names order (computed on pre-reduction Xn)
        X_train = X_base
        if use_text_sim_features and text_features is not None:
            try:
                # Build text matrix [C, D]
                T_list: List[np.ndarray] = []
                for cname in self.class_names:
                    tf = text_features.get(cname, None)
                    if tf is None:
                        raise KeyError(f"Missing text feature for class: {cname}")
                    if isinstance(tf, torch.Tensor):
                        tf = tf.detach().cpu().numpy()
                    tf = np.asarray(tf, dtype=np.float32).reshape(-1)
                    # Normalize
                    n = np.linalg.norm(tf) + 1e-8
                    T_list.append(tf / n)
                T = np.stack(T_list, axis=0)  # [C, D]
                # Cosine similarity since both sides normalized
                S = Xn @ T.T  # [N, C] computed from pre-reduction features
                # Per-sample z-score
                mu = S.mean(axis=1, keepdims=True)
                sd = S.std(axis=1, keepdims=True) + 1e-8
                Sz = (S - mu) / sd
                X_train = np.concatenate(
                    [X_base, (float(beta) * Sz).astype(np.float32)], axis=1
                )
            except Exception:
                X_train = X_base

        self.fit(X_train, y_list)

    # --------------------------- Inference ---------------------------
    def predict_from_features(
        self, feat: Union[np.ndarray, torch.Tensor]
    ) -> Tuple[str, Dict[str, float]]:
        """Predict from a single L2-normalized embedding vector [D]."""
        if not self.is_trained:
            raise RuntimeError("SVMClassifier is not trained")
        if isinstance(feat, torch.Tensor):
            feat = feat.detach().cpu().numpy()
        feat = feat.reshape(1, -1)
        # Ensure normalization
        feat = feat / (np.linalg.norm(feat, axis=1, keepdims=True) + 1e-8)

        # Map scores aligned to underlying model.classes_ order to avoid LabelEncoder dependency
        import numpy as _np

        classes_idx = getattr(
            self.model, "classes_", _np.arange(len(self.label_encoder.classes_))
        )
        ordered_names = list(self.label_encoder.classes_)
        if self.model.probability:
            proba = self.model.predict_proba(feat)[0]  # [C]
            scores = {}
            for i, ci in enumerate(classes_idx):
                ci = int(ci)
                if 0 <= ci < len(ordered_names):
                    scores[ordered_names[ci]] = float(proba[i])
        else:
            # Use decision function and min-max normalize to [0, 1]
            dec = self.model.decision_function(feat).astype(np.float32).reshape(-1)
            lo, hi = float(dec.min()), float(dec.max())
            if hi > lo:
                norm = (dec - lo) / (hi - lo)
            else:
                norm = _np.zeros_like(dec)
            scores = {}
            for i, ci in enumerate(classes_idx):
                ci = int(ci)
                if 0 <= ci < len(ordered_names):
                    scores[ordered_names[ci]] = float(norm[i])

        # Pick best
        best_cls = max(scores.items(), key=lambda x: x[1])[0]
        return best_cls, scores

    # --------------------------- Persistence ---------------------------
    def save(self, path: Union[str, Path]) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        meta = {
            "class_names": list(self.label_encoder.classes_),
            "cfg": self.cfg.__dict__,
            "feature_dim": self.feature_dim,
            "reducer_blob": self.reducer.serialize()
            if getattr(self, "reducer", None) is not None
            else None,
            "reducer_output_dim": self.reducer.output_dim
            if getattr(self, "reducer", None) is not None
            else None,
        }
        if joblib is None:
            raise ImportError("joblib is required to save SVM models")
        joblib.dump({"model": self.model, "meta": meta}, str(path))
        # Also persist classes.py next to the model for downstream usage
        try:
            _save_classes_py(path.parent, list(self.label_encoder.classes_))
        except Exception:
            pass
        return path

    @classmethod
    def load(cls, path: Union[str, Path]) -> "SVMClassifier":
        if joblib is None:
            raise ImportError("joblib is required to load SVM models")
        path = Path(path)
        data = joblib.load(str(path))
        meta = data.get("meta", {})
        cfg = SVMConfig(**meta.get("cfg", {}))
        # Prefer classes.py next to the model; fallback to embedded metadata
        override = _load_classes_from_py(path.parent)
        class_names = override if override else meta.get("class_names", [])
        inst = cls(class_names=class_names, cfg=cfg)
        inst.model = data.get("model", None)
        inst.feature_dim = meta.get("feature_dim", None)
        try:
            blob = meta.get("reducer_blob", None)
            if blob is not None:
                inst.reducer = DimensionalityReducer.deserialize(blob)
        except Exception:
            inst.reducer = None
        return inst


def create_svm_classifier(
    class_names: List[str], cfg: Optional[SVMConfig] = None
) -> SVMClassifier:
    return SVMClassifier(class_names=class_names, cfg=cfg)
