desc_dict = {
    "白鹇": "Lophura nycthemera is a large bird (70-115cm). Males: blue-black crest/belly, red face, white wings/back with black 'V' marks. Females: brown with a dark crest, reddish face, and black markings below.",
    "豹猫": "Prionailurus bengalensis (36-66 cm, 1.5-5 kg) has black eye stripes, white-spotted ears, and a white facial stripe. Its flanks are spotted (not barred), and its long tail is ringed with a black tip.",
    "藏酋猴": "Macaca thibetana has a central hair part and thick whiskers. Males have a flesh-colored face and white eye-rings; females have a red face and pink eye-rings. Face color changes with age from white (juvenile) to red (adult) to purplish-black.",
    "赤腹松鼠": "Callosciurus erythraeus is a slender squirrel (178–223 mm) with a short snout and a tail nearly its body length. It has two pairs of abdominal nipples.",
    "赤狐": "Vulpes vulpes, the largest fox (~70 cm), has a slender body, pointed snout, large black-tipped ears, and a bushy, white-tipped tail. Known for a strong odor from scent glands.",
    "穿山甲": "Manis javanica is a small (40-58 cm, 3-5 kg), scaly mammal. Toothless, it uses a long, sticky tongue to eat. Its body is protected by 15-18 rows of overlapping dark scales with hairs underneath.",
    "东北虎": "Panthera tigris altaica is a muscular tiger with a large head and thick, reddish-orange fur. It is distinguished by its black stripes and a white chest and mane.",
    "狗獾": "Meles meles has a conical head, prominent snout, and three white head stripes. Its sandy or grey-white back contrasts sharply with its dark limbs and underparts.",
    "果子狸": "Paguma larvata (40–70 cm, 3–7 kg) is stout-bodied with a blunt snout and large ears. Features semi-retractable claws, anal scent glands, and two pairs of nipples in females.",
    "貉": "Nyctereutes procyonoides is a small, stocky canid (45-66 cm, 3-6 kg) with short legs and a bushy tail. It is characterized by its brownish-grey fur and a distinctive black facial mask.",
    "黑麂": "Muntiacus crinifrons (≈35 kg) is distinguished by golden forehead tufts and short male antlers. Its dark brown-black coat contrasts with a white ventrum (belly).",
    "黑熊": "Ursus thibetanus (110-189 cm, 40-200 kg) is a robust black bear with a white chin and a distinctive 'V'-shaped white chest patch. It has a round head and non-retractable claws.",
    "华南兔": "Lepus sinensis (1.5–2.5 kg, ~40 cm) is a reddish-brown/sandy rabbit with a distinctive nape patch, pale eye-ring, and a bicolored tail (dark above, pale below).",
    "黄喉貂": "Martes flavigula (56-65 cm, 2-3 kg) is a slender mustelid known for vivid coloration: a dark brown-black body and tail contrasting with a bright yellow throat and chest.",
    "黄鼬": "Mustela sibirica is a medium-sized weasel with black facial markings, a white muzzle, and yellowish-brown to dark brown fur. It has a lighter underbelly and strong anal scent glands.",
    "金钱豹": "Panthera pardus (1–1.5 m, 50–100 kg) is a sleek predator with a yellow coat covered in distinctive black rosettes (like coins). It has a long tail and powerful limbs with retractable claws.",
    "毛冠鹿": "Elaphodus cephalophus is named for its dark forehead tuft. It has short, unbranched antlers, protruding upper canines ('tusks'), and a dark coat (near-black in winter) with white-tipped neck hairs.",
    "梅花鹿": "Cervus nippon (140-170 cm long, 100-150 kg) is a deer whose males grow 3-4 tined antlers, where the brow tine angles forward from the base and the main beam curves outward.",
    "猕猴": "Macaca mulatta (~50 cm) is a robust monkey with similar-length limbs and opposable thumbs. Its tail length is highly variable (from absent to long), and it has a distinct raised ridge on its forehead.",
    "牛": "Bovini are large, stout-bodied bovines, often with horns in both sexes. Some breeds have a shoulder hump. As ruminants, they possess a four-chambered stomach.",
    "狍": "Capreolus pygargus is a small to medium-sized deer (126-144 cm long, ~32-49 kg) with long hind legs and a very short tail (2-4 cm). Males are typically heavier than females.",
    "食蟹獴": "Herpestes urva (36-52 cm, 1-2.3 kg) is a mongoose with a pointed snout, webbed feet, and a grizzled sandy-brown coat. It is identified by distinctive yellowish-white stripes on its face.",
    "小麂": "Muntiacus reevesi is a small deer with slender limbs. Males have short antlers. Its coloration features dark brownish-yellow fur, distinctive black forehead stripes, and vivid orange-yellow rump patches.",
    "野猪": "Sus scrofa is a medium-sized mammal (1.5-2 m, 90-200 kg) with a dark brown to black coat of coarse guard hairs over a soft undercoat. Its shoulder height is about 90 cm.",
    "鼬獾": "Melogale moschata has a pointed snout, long front claws, and coarse grayish fur. Key markings are a white head stripe and facial patch. Its underparts are paler, and its coat is grayer in winter.",
    "中国豪猪": "Hystrix hodgsoni is a large porcupine with brown fur and a white dorsal stripe of bristle-like quills. Its body is covered in hollow quills, longest on the rump (~300mm), and it has a pale chest band.",
    "中华鬣羚": "Capricornis milneedwardsii is a bovid with a dark, coarse coat and reddish-gray highlights on its mane and legs. Features include short, backward-curving horns and a shaggy dorsal mane.",
    "猪獾": "Arctonyx collaris is a large, stout mustelid (65–104 cm, 7–15 kg). It is characterized by a thick neck, a hairless, pig-like snout, and powerful limbs with long, curved claws.",
    "紫貂": "Martes zibellina is a slender, arboreal mammal (~40 cm, 1 kg) with a bushy tail (~12 cm). It is adapted for tree life with strong limbs, semi-retractable claws, and large triangular ears.",
    "人类": "Homo sapiens, a hominid species whose lineage emerged in East Africa ~5 million years ago (as evidenced by fossils and DNA), produced language, religion, art, and science through our advanced cognition, aesthetic sense, and expressive drive."
}